services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pg-vector
    restart: unless-stopped
    environment:
      POSTGRES_USER: shiven
      POSTGRES_PASSWORD: root
      POSTGRES_DB: linnkedout_db
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shiven -d linnkedout_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis-token-store
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
  redisdata: 